# train_recognizer.py
import cv2
import numpy as np
import os

TRAINING_DIR = "TrainingImages"
TRAINER_FILE = "trainer.yml"
NAMES_FILE = "names.txt"

def train():
    recognizer = cv2.face.LBPHFaceRecognizer_create()
    faces = []
    ids = []
    label_map = {}
    current_id = 0

    if not os.path.isdir(TRAINING_DIR):
        print("No TrainingImages folder found. Create TrainingImages/PersonName/ and add images.")
        return

    for person_name in sorted(os.listdir(TRAINING_DIR)):
        person_path = os.path.join(TRAINING_DIR, person_name)
        if not os.path.isdir(person_path):
            continue
        if person_name not in label_map:
            label_map[person_name] = current_id
            current_id += 1
        label_id = label_map[person_name]
        for img_name in os.listdir(person_path):
            img_path = os.path.join(person_path, img_name)
            img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            if img is None:
                continue
            faces.append(img)
            ids.append(label_id)

    if len(faces) == 0:
        print("No face images found. Add images and try again.")
        return

    recognizer.train(faces, np.array(ids))
    recognizer.write(TRAINER_FILE)
    print(f"Trainer saved to {TRAINER_FILE}")

    # write ordered names
    ordered = [None] * len(label_map)
    for name, idx in label_map.items():
        ordered[idx] = name
    with open(NAMES_FILE, "w") as f:
        for n in ordered:
            f.write(n + "\n")
    print(f"Names written to {NAMES_FILE}")

if _name_ == "_main_":
    train()